#!/usr/bin/env python3
"""Generate everything that carries the SOZVON mark from the one master.

The mark lives in static/sozvon-mark.svg as a single filled outline.  Four
other files need the same geometry, in three different dialects, and keeping
them in step by hand is how a logo ends up half-updated:

    static/theme/favicon.svg              the icon every page points at
    desktop/src/renderer/mark.svg         the app bar's lockup
    desktop/assets/icon.svg               source for the Windows .ico
    android/.../drawable/ic_sozvon.xml      the launcher icon's foreground

Run it after editing the master, and commit the lot together:

    python contrib/build-mark-assets.py

The .ico is a build step of its own, since it needs sharp:

    npm --prefix desktop run icon

Regenerating the *master* is a different matter: it is traced from a raster
that is not in this repository, the identity having no vector original.  See
contrib/trace-mark.py, which does the tracing, and the comment at the top of
the master for how closely the current one follows.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MASTER = ROOT / "static" / "sozvon-mark.svg"

# The glyph's own box, and how much of a square plate it fills.  The identity
# sets the handset at about seven tenths of the icon's height, centred.
GLYPH_W, GLYPH_H = 218.0, 590.0
FILL = 0.72

# The master is a hairline: its line is 8 units of a 218-unit width, or 3.7%.
# That is right at 512px and gone at 16, where it works out to a sixth of a
# pixel -- which is why the identity carries a heavier cut for small sizes.
# Stroking the outline in its own colour widens the band by this much, to the
# 32 units the identity's own micro cut uses.
THICKEN = 24.0

# An XML comment may not contain a double hyphen, and three of the four
# targets are XML, so this line keeps to single ones.
GENERATED = "Generated by contrib/build-mark-assets.py; do not edit here."


def path_data():
    svg = MASTER.read_text(encoding="utf-8")
    m = re.search(r'\sd="([^"]+)"', svg)
    if not m:
        sys.exit(f"no path found in {MASTER}")
    return m.group(1)


def placement(box):
    """Scale and offset that centre the glyph on a square plate of `box`."""
    scale = box * FILL / GLYPH_H
    return scale, (box - GLYPH_W * scale) / 2, (box - GLYPH_H * scale) / 2


def ink(d, cls=None, colour=None, thicken=0.0):
    """The glyph, optionally widened.  A stroke in the fill's own colour adds
    half its width to each side of the band, so the line grows without the
    drawing changing shape."""
    attrs = f'class="{cls}"' if cls else f'fill="{colour}"'
    if thicken:
        if colour:
            attrs += f' stroke="{colour}"'
        attrs += (f' stroke-width="{thicken:.1f}" '
                  'stroke-linejoin="round" stroke-linecap="round"')
    return f'<path {attrs} fill-rule="evenodd" d="{d}"/>'


def favicon(d):
    s, dx, dy = placement(64)
    glyph = ink(d, cls="ink", thicken=THICKEN)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- SOZVON app icon / favicon — identity system v1.1.
     {GENERATED}

     The identity reserves the stacked SOZ/VON composition for large sizes and
     calls for the mark alone at favicon sizes, so this is the handset on its
     plate rather than the wordmark.

     One file for both themes: an SVG favicon is rendered with its own
     stylesheet, so prefers-color-scheme decides which way round the plate and
     the ink go.  A browser that ignores the media query gets the dark cut,
     which is the identity's primary.

     Part of the deployment theme hook: a site may replace static/theme/ at
     deploy time, and this file is the icon every page points at. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <style>
    .plate {{ fill: #000; }}
    .ink {{ fill: #fff; stroke: #fff; }}
    @media (prefers-color-scheme: light) {{
      .plate {{ fill: #fff; }}
      .ink {{ fill: #000; stroke: #000; }}
    }}
  </style>
  <rect class="plate" width="64" height="64" rx="10"/>
  <g transform="translate({dx:.3f} {dy:.3f}) scale({s:.5f})">
    {glyph}
  </g>
</svg>
"""


def desktop_icon(d):
    s, dx, dy = placement(512)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- SOZVON desktop app icon — identity system v1.1.
     {GENERATED}

     Source for assets/icon.ico, which Windows shows on the taskbar, the
     shortcut and the installer.  Rebuild it with the desktop's `icon`
     script, which is what turns this file into the .ico.

     The plate stays black whichever theme the desktop is in.  A launcher icon
     is not chrome that follows the user's setting; it is how the app is
     recognised, and half the places Windows draws it have a background of
     their own. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" rx="80" fill="#000"/>
  <g transform="translate({dx:.3f} {dy:.3f}) scale({s:.5f})">
    <path fill="#fff" fill-rule="evenodd" d="{d}"/>
  </g>
</svg>
"""


def desktop_icon_small(d):
    s, dx, dy = placement(512)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- SOZVON desktop app icon, the cut for small sizes.  {GENERATED}
     Same drawing with the line widened, for the 16 to 48px entries of the
     .ico: at 16px the master's hairline is a sixth of a pixel and the icon
     comes out an empty rounded square. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" rx="80" fill="#000"/>
  <g transform="translate({dx:.3f} {dy:.3f}) scale({s:.5f})">
    {ink(d, colour="#fff", thicken=THICKEN)}
  </g>
</svg>
"""


def bar_mark(d):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- SOZVON mark for the desktop app bar.  {GENERATED}
     A copy of static/sozvon-mark.svg: the bar is loaded from the filesystem
     and cannot reach the server's copy.  Painted as a CSS mask, so it takes
     currentColor and needs no second cut for the light theme. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 218 590" width="218" height="590">
  <path fill="#000" fill-rule="evenodd" d="{d}"/>
</svg>
"""


def android_icon(d):
    # An adaptive icon is a 108dp square of which only the middle 72dp is
    # certain to be shown -- the launcher may mask, rotate or parallax the
    # rest -- so the glyph is placed against that inner square, not the whole.
    box = 108.0
    safe = 72.0
    s = safe * 0.92 / GLYPH_H
    dx = (box - GLYPH_W * s) / 2
    dy = (box - GLYPH_H * s) / 2
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- SOZVON launcher icon, foreground layer.  {GENERATED}
     The background is a colour of its own (sozvon_icon_bg), fixed rather than
     themed: a launcher icon that followed the device's dark mode would put
     white ink on a white plate the moment the user switched. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group
        android:translateX="{dx:.3f}"
        android:translateY="{dy:.3f}"
        android:scaleX="{s:.5f}"
        android:scaleY="{s:.5f}">
        <path
            android:fillColor="#FFFFFF"
            android:fillType="evenOdd"
            android:pathData="{d}"/>
    </group>
</vector>
"""


def main():
    d = path_data()
    targets = {
        ROOT / "static" / "theme" / "favicon.svg": favicon(d),
        ROOT / "desktop" / "src" / "renderer" / "mark.svg": bar_mark(d),
        ROOT / "desktop" / "assets" / "icon.svg": desktop_icon(d),
        ROOT / "desktop" / "assets" / "icon-small.svg": desktop_icon_small(d),
        ROOT / "android" / "app" / "src" / "main" / "res" / "drawable"
        / "ic_sozvon.xml": android_icon(d),
    }
    for path, text in targets.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"  {path.relative_to(ROOT)}  {len(text)} bytes")
    print(f"from {MASTER.relative_to(ROOT)} ({len(d)} bytes of path)")


if __name__ == "__main__":
    main()
